import matplotlib.pyplot as plt
import numpy as np

ser = np.genfromtxt('ser-benchmark.data', delimiter=' ')  
vec = np.genfromtxt('vec-benchmark.data', delimiter=' ')
plt.figure()
plt.title('Vector multiplication benchmark loop = (10M * X FLOP)')
plt.plot(ser[:, 0], ser[:, 3], marker='^', label='serial')
plt.plot(vec[:, 0], vec[:, 1], marker='o', label='MIN vectorized')
plt.plot(vec[:, 0], vec[:, 2], marker='o', label='MAX vectorized')
plt.plot(vec[:, 0], vec[:, 3], marker='o', label='AVG vectorized')
plt.xlabel('FLOP per loop iteration')
plt.ylabel('Time [s]')
plt.legend()
#plt.show()
plt.savefig('time_vec_vs_ser_vector_op.pdf')

plt.figure()
plt.title('Vector multiplication benchmark it = 10M')
plt.plot(ser[:, 0], vec[:, 3] / vec[:, 3], marker='^', label='serial')
plt.plot(vec[:, 0], ser[:, 3] / vec[:, 1], marker='o', label='MIN vectorized')
plt.plot(vec[:, 0], ser[:, 3] / vec[:, 2], marker='o', label='MAX vectorized')
plt.plot(vec[:, 0], ser[:, 3] / vec[:, 3], marker='o', label='AVG vectorized')
plt.xlabel('FLOP per loop iteration')
plt.ylabel('Speedup')
plt.legend()
#plt.show()
plt.savefig('speedup_vec_vs_ser_vector_op.pdf')
